// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iycvmpsdftkiondvoozc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Y3ZtcHNkZnRraW9uZHZvb3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzgxODEsImV4cCI6MjA2MDgxNDE4MX0.ZTY9uwJBQ5cMJ8W55DbQL-M4LOSb1sKC371Bs5LQmN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);